language: node_js
sudo: false
node_js:
  - v0.12
  - v4
  - v5
  - v6

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@3
  - npm set fetch-retry-maxtimeout 180000
install:
  - npm install
before_script:
  - npm i -g tslint
script:
  - npm run test -- --concurrency 1
after_success:
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run coveralls; fi;
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run release; fi;

after_failure: "cat /home/travis/build/mosjs/mos/packages/mos-core/npm-debug.log"
