language: node_js
sudo: false
node_js:
  - v4
  - v6
  - v8

cache:
  directories:
    - $HOME/.pnpm-registry

before_install:
  - npm install -g pnpm pnpmr
  - npm set fetch-retry-maxtimeout 180000
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm config set store-path ~/.store; fi;
install:
  - pnpm install
  - pnpm run link
  - pnpmr install
script:
  - pnpmr test
after_success:
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run coveralls; fi;
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run release; fi;

after_failure: "cat /home/travis/build/mosjs/mos/packages/mos-core/npm-debug.log"
