language: node_js
sudo: false
node_js:
  - v4
  - v6

before_install:
  - npm set user-agent node/4
  - npm install -g pnpm@0.64.2
  - npm set fetch-retry-maxtimeout 180000
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm config set store-path ~/.store; fi;
install:
  - npm install
  - pnpm run bootstrap
script:
  - npm run test -- --concurrency 1
after_success:
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run coveralls; fi;
  - if [[ $TRAVIS_NODE_VERSION == "v6" ]]; then npm run release; fi;

after_failure: "cat /home/travis/build/mosjs/mos/packages/mos-core/npm-debug.log"
