environment:
  matrix:
    - nodejs_version: '0.12'
    - nodejs_version: '4'
    - nodejs_version: '5'
    - nodejs_version: '6'
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
matrix:
  fast_finish: true
build: off
version: '{build}'
test_script:
  - npm test
